Выставить отступ в категориях в соответствии с баг репортом
Information-platform-about-IT-companies/Front-main pull request #124
Opened 2023-12-01 21:39 UTC by MothersCoder

2023-12-02 06:31 UTC, ArturKhelshtein requested changes

2023-12-02 06:31 UTC, ArturKhelshtein commented on src/components/Footer/Footer.scss
> +  position: relative;
зачем добавлено?

2023-12-02 06:31 UTC, ArturKhelshtein commented on src/components/Header/Header.scss
> +  max-width: 1200px; */
стоит убрать закментированный код.

2023-12-02 06:31 UTC, ArturKhelshtein commented on src/components/Header/Header.scss
> +  background-color: var(--background);
не понял зачем, можно поясение

2023-12-02 14:55 UTC, vvvolkova-92 requested changes

2023-12-02 14:55 UTC, vvvolkova-92 commented on src/components/Footer/Footer.scss
> +  position: relative;
тот же вопрос)

2023-12-02 14:56 UTC, vvvolkova-92 commented on src/components/Header/Header.scss
> +  max-width: 1200px; */
+

2023-12-02 14:56 UTC, vvvolkova-92 commented on src/components/Header/Header.scss
> +  background-color: var(--background);
+

2023-12-02 20:45 UTC, MothersCoder commented on src/components/Footer/Footer.scss
> +  position: relative;
подтянулся кусок кода с фиксации header, что я удалял
тут это и далее лишнее, все удалил

2023-12-03 20:39 UTC, ArturKhelshtein approved these changes

2023-12-03 21:44 UTC, merged