исправить на service
Information-platform-about-IT-companies/Front-main pull request #134
Opened 2023-12-02 17:40 UTC by gineff

2023-12-02 19:19 UTC, ArturKhelshtein requested changes

2023-12-02 19:19 UTC, ArturKhelshtein commented on src/hooks/useFetchCompanies.js
> +        ? filterServices.map((id) => ["service", id])
по моему не только тут надо поправить на service

2023-12-02 19:23 UTC, gineff commented on src/hooks/useFetchCompanies.js
> +        ? filterServices.map((id) => ["service", id])
Я думаю, сейчас не самое удачное время, чтобы рефакторить сложный работающий код и потом ловить баги

2023-12-02 23:32 UTC, ArturKhelshtein approved these changes

2023-12-03 21:51 UTC, vvvolkova-92 approved these changes

2023-12-03 21:51 UTC, merged