Feature/routing
Information-platform-about-IT-companies/Front-main pull request #17
Opened 2023-10-19 18:06 UTC by MothersCoder

Сделал роуты по всем основным сценариям, также добавил основные компоненты, с версией дева от 21.00 все конфликты решены

2023-10-19 18:32 UTC, ArturKhelshtein approved these changes

2023-10-20 05:32 UTC, Alina1859 approved these changes

2023-10-20 07:29 UTC, vvvolkova-92 requested changes

2023-10-20 07:29 UTC, vvvolkova-92 commented on src/components/ProtectedRoute/ProtectedRoute.js
> +// eslint-disable-next-line arrow-body-style, react/function-component-definition
Мы правила линтера в коде не отключаем

2023-10-20 08:50 UTC, vvvolkova-92 approved these changes

2023-10-20 10:34 UTC, Zvonarev23 approved these changes

2023-10-20 10:38 UTC, merged