Реализовать компонент input
Information-platform-about-IT-companies/Front-main pull request #21
Opened 2023-10-20 19:50 UTC by MothersCoder

2023-10-21 06:38 UTC, Alina1859 approved these changes

2023-10-21 20:34 UTC, ArturKhelshtein approved these changes

2023-10-22 09:04 UTC, vvvolkova-92 requested changes

2023-10-22 09:04 UTC, vvvolkova-92 commented on src/UI-KIT/Input/Input.jsx
> +    </>
предусмотреть span для вывода ошибки (дизайн запросила)

2023-10-22 09:04 UTC, vvvolkova-92 commented on src/UI-KIT/Input/Input.jsx
> +  minLength: PropTypes.number,
в конце убрать лишнее )

2023-10-22 09:04 UTC, vvvolkova-92 commented on src/UI-KIT/Input/Input.jsx
> +export default Input;
Не забудь сразу сделать стори для Инпута

2023-10-22 09:04 UTC, vvvolkova-92 commented on src/UI-KIT/Input/Input.scss
файл со стилями пустой

2023-10-26 09:09 UTC, merged