Feauture/lable
Information-platform-about-IT-companies/Front-main pull request #23
Opened 2023-10-22 14:46 UTC by Alina1859

2023-10-23 11:54 UTC, vvvolkova-92 requested changes

2023-10-23 11:54 UTC, vvvolkova-92 commented on src/UI-KIT/Label/Label.jsx
> +    <div className={`label ${extClassName}`} {...props}>
по-хорошему не нужна лишняя обертка в виде <div>
можно просто возвращать стилизованный <span>, вместо <p> - все таки он для параграфа используется, а у нас будет 1-2 слова.

2023-10-23 11:54 UTC, vvvolkova-92 commented on src/UI-KIT/Label/Label.jsx
> +      <p className="label_title">{children}</p>
и можно будет не children пробрасывать , а пропс title (это по желанию)

2023-10-23 12:16 UTC, ArturKhelshtein reviewed
согласен с предложениями @vvvolkova-92

2023-10-24 08:45 UTC, Zvonarev23 requested changes

2023-10-24 08:50 UTC, Alina1859 commented on src/UI-KIT/Label/Label.jsx
> +      <p className="label_title">{children}</p>
Я тоже думала про ссылку. Но когда я этот вопрос поднимала, мы решили, что, какие-то будут кликабельны, какие-то нет. Но с Дашей не обсуждали. В итоге, я сделала по варианту Виолетты, спан. Он будет оборачиваться Link-ом в случае, если кликабельно, ссылка в любом случае не нужна.

2023-10-24 08:51 UTC, vvvolkova-92 commented on src/UI-KIT/Label/Label.jsx
> +      <p className="label_title">{children}</p>
лейблы будут кликабельны (услуги) и не кликабельны (отрасли) 
так что делать универсальный, а при рендеренге оторачивать в `<Link>`

2023-10-24 10:20 UTC, ArturKhelshtein approved these changes

2023-10-24 10:23 UTC, Zvonarev23 approved these changes

2023-10-24 10:33 UTC, vvvolkova-92 approved these changes

2023-10-24 10:33 UTC, merged