Верстка компонента Form
Information-platform-about-IT-companies/Front-main pull request #24
Opened 2023-10-22 16:02 UTC by Zvonarev23

2023-10-23 09:03 UTC, Alina1859 approved these changes

2023-10-23 12:03 UTC, vvvolkova-92 requested changes

2023-10-23 12:03 UTC, vvvolkova-92 commented on src/UI-KIT/Form/Form.scss
> +  background-color: transparent;
у всех форм одиковые падинги и бэкграунд
добавь)

2023-10-23 12:26 UTC, ArturKhelshtein approved these changes

2023-10-23 13:37 UTC, Zvonarev23 commented on src/UI-KIT/Form/Form.scss
> +  background-color: transparent;
> у всех форм одиковые падинги и бэкграунд добавь)

Мы же договорились делать универсальную форму) Или ты хочешь для фильтрации создать уникальную? https://joxi.ru/5mdJdKvHJx18gA 

Плюс я заметил изменения в UI и формы будут разного цвета. Лучше будет сделать обертку для контента и ему задать бэкграунд с паддингами. Обрати внимание, что на главной они сиреневые, а в личной кабинете голубые

2023-10-24 08:40 UTC, vvvolkova-92 commented on src/UI-KIT/Form/Form.scss
> +  background-color: transparent;
Для фильтра другую

2023-10-24 15:52 UTC, MothersCoder approved these changes

2023-10-24 21:01 UTC, merged