Сделала компонент Checkbox и storybook к нему
Information-platform-about-IT-companies/Front-main pull request #25
Opened 2023-10-23 08:59 UTC by Alina1859

2023-10-23 14:36 UTC, vvvolkova-92 requested changes

2023-10-23 14:36 UTC, vvvolkova-92 commented on src/UI-KIT/Checkbox/Checkbox.jsx
> +export function Checkbox({ title, value, onChange, ...props }) {
нужно пробрасывать 
- id, чтобы указывать его в `<label  htmlFor >` - у нас может быть и будет много чекбоксов
- name

2023-10-23 14:36 UTC, vvvolkova-92 commented on src/UI-KIT/Checkbox/Checkbox.jsx
> +    setisChecked(!isChecked);
нужно использоваться предыдущее состояние

2023-10-23 14:36 UTC, vvvolkova-92 commented on src/UI-KIT/Checkbox/Checkbox.jsx
> +  function handleChange(e) {
е не нужен тут)

2023-10-23 14:36 UTC, vvvolkova-92 commented on src/UI-KIT/Checkbox/Checkbox.jsx
> +  value: PropTypes.bool.isRequired,
а что ты подразумеваешь под передачей `value`? почему булевый тип? 
по сути `value` можно не пробрасывать, а указать `id`

2023-10-24 14:47 UTC, Zvonarev23 requested changes
Обычно пишется универсальный обработчик в родительском компоненте формы (твой handleChange) который прокидывается пропсом внутрь Checkbox. Иначе как форма будет узнавать об изменении состояний checkbox?) 

Нам же нужно получать данные для отправки формы. Может конечно я чего-то не понимаю, но кажется должно быть именно так.

2023-10-24 20:56 UTC, vvvolkova-92 commented
Итого мы должны получить максимально универсальный чекбокс. 
Значит пропсами прокидывать в него: id, name, label, onChange, и ..rest(...props)
label - для заголовка
onChange - для изменения состояния + что-то изменять/запомнить для отправки формы (например, выборка услуг в фильтре - их же нужно как-то обозначить. И делается это не внутри компонента)
id - чтобы связаться label и checkbox
value - не пробрасываем, вместо него достаточно будет использовать id

Внимательно посмотри код и то, что мы тут написали - жду рефакторинг <3 (p.s ночью код редактировали, не забудь получить свежий develop)

2023-10-25 16:22 UTC, merged