Refactor/link with icon
Information-platform-about-IT-companies/Front-main pull request #40
Opened 2023-10-28 16:12 UTC by MothersCoder

добавил сценарий линка с icon

2023-10-29 21:04 UTC, ArturKhelshtein requested changes

2023-10-29 21:04 UTC, ArturKhelshtein commented on src/UI-KIT/Link/LinkItem.scss
> +  display: flex;
стоит использовать миксин

2023-10-29 21:04 UTC, ArturKhelshtein commented on src/UI-KIT/Link/LinkItem.scss
> +  display: flex;
стоит использовать миксин

2023-10-30 16:40 UTC, MothersCoder commented on src/components/Header/Header.jsx
> +  userData: PropTypes.string,
Не совсем понял коммент - признак авторизован или нет указан как обязательный, а данные пользователя не указаны как обязательные именно по той причине, что они могут быть (пользователь авторизован) или нет (пользователь не авторизован)

2023-10-30 22:38 UTC, merged