Реализовать компонент footer
Information-platform-about-IT-companies/Front-main pull request #41
Opened 2023-10-29 19:37 UTC by MothersCoder

2023-10-29 21:15 UTC, ArturKhelshtein requested changes

2023-10-29 21:15 UTC, ArturKhelshtein commented on src/components/App/App.jsx
> +      <Footer />
а почему не внизу?

2023-10-29 21:15 UTC, ArturKhelshtein commented on src/components/Footer/Footer.jsx
> +  const conditions =
рекомендация: не говорящее имя, логичнее isLogoHide

2023-10-29 21:15 UTC, ArturKhelshtein commented on src/components/Footer/Footer.jsx
> +      <ul className={`footer__link ${conditions ? "footer__link_full" : ""}`}>
вопрос: а стоило ли оборачивать в список?

2023-10-29 21:15 UTC, ArturKhelshtein commented on src/components/Footer/Footer.scss
> +  width: 128px;
вопрос: а лого не в размерах, зачем задавать жестко размеры?

2023-10-29 21:15 UTC, ArturKhelshtein commented on src/images/Octopus-footer.svg
ой, вроде же логотип должен быть нормальный. хотя сейчас по макету вообще не вижу логотипа в футере

2023-10-30 16:32 UTC, MothersCoder commented on src/components/App/App.jsx
> +      <Footer />
согласен, поправил

2023-10-30 16:33 UTC, MothersCoder commented on src/components/Footer/Footer.jsx
> +      <ul className={`footer__link ${conditions ? "footer__link_full" : ""}`}>
в новом дизайне нет, смысла в обертке нет, а в старой реализации это нужно было для распределения блоков

2023-10-30 16:33 UTC, MothersCoder commented on src/components/Footer/Footer.scss
> +  width: 128px;
я задавал лого фоном, там надо размер указывать, но в новом дизайне нет лого - нет проблемы :)

2023-10-30 16:34 UTC, MothersCoder commented on src/images/Octopus-footer.svg
сделал футер как на UI

2023-10-30 16:37 UTC, MothersCoder commented on src/components/Footer/Footer.jsx
> +  const conditions =
с новым дизайном этот блок лишний, выпилил

2023-10-30 21:13 UTC, vvvolkova-92 commented on src/components/App/App.jsx
> +      <Footer />
Он вообще нигде в эпе быть не должен =)

2023-10-30 21:18 UTC, vvvolkova-92 commented
Я залью в девелоп, но сделаю рефактор.

2023-10-30 21:18 UTC, merged