Feature/pagination
Information-platform-about-IT-companies/Front-main pull request #69
Opened 2023-11-07 11:29 UTC by Zvonarev23

2023-11-07 17:49 UTC, ArturKhelshtein requested changes

2023-11-07 17:49 UTC, ArturKhelshtein commented on src/components/Pagination/Pagination.scss
> +      background: linear-gradient(180deg, #605ed6 -0.01%, #5c9ad2 100.02%);
это переменная $gradient-blue

2023-11-07 17:49 UTC, ArturKhelshtein commented on src/components/Pagination/Pagination.scss
> +        background: linear-gradient(#605ed6, #5c9ad2);
а это точно не обычный градиент?  $gradient-blue

2023-11-07 17:49 UTC, ArturKhelshtein commented on src/components/Pagination/Pagination.scss
> +@import "assets/style/variables";
подключение д.б. через assets/style/main

2023-11-08 08:23 UTC, Zvonarev23 commented on src/components/Pagination/Pagination.scss
> +        background: linear-gradient(#605ed6, #5c9ad2);
Этот не из переменных

2023-11-08 08:23 UTC, Zvonarev23 commented on src/components/Pagination/Pagination.scss
> +      background: linear-gradient(180deg, #605ed6 -0.01%, #5c9ad2 100.02%);
> это переменная $gradient-blue

Согласен)

2023-11-09 19:19 UTC, merged