Feauture/validation profile
Information-platform-about-IT-companies/Front-main pull request #78
Opened 2023-11-11 12:35 UTC by Alina1859

2023-11-11 14:02 UTC, ArturKhelshtein requested changes

2023-11-11 14:02 UTC, ArturKhelshtein commented on src/services/constants.js
> +  /^(?!.* )(?!^\d+$)[a-zA-Z0-9._~\-|:?#[\]\\@!$&'{}()*+,/;=]{8,30}$/gim;
- почему перед слешем не стоит экранирующий символ?
- в пароль надо добавить символы %, ^, ",  №,  и кирилицу :)
- надо убрать не чувствительность к регистру
/^(?!.* )(?!^\d+$)[a-zA-Zа-яА-ЯёЁ0-9._~\-|:?#№[\]\\@"!$%^&'{}()*+,\/;=]{8,30}$/gm

2023-11-11 15:02 UTC, Alina1859 commented on src/services/constants.js
> +  /^(?!.* )(?!^\d+$)[a-zA-Z0-9._~\-|:?#[\]\\@!$&'{}()*+,/;=]{8,30}$/gim;
а какой именно слэш ты хочешь экранировать? потому что при использовании такой регулярки ^(?!.* )(?!^\d+$)[a-zA-Z0-9._~\-|:?#[]\\@!$&'{}()*+,\/;=]{8,30}$   
выдает ошибку еслинт  Line 145:55:  Unnecessary escape character: \/  no-useless-escape .  отключить ее я не могу, хаски ругается. 
регуряка твоего вида выдает ошибку Parsing error: Unexpected token. на этом ;=] участке что происходит из-за того, что ты убрал \ из скобок [] 
по поводу символов, чувствительности и кириллицы - поправила))
/^(?!.* )(?!^\d+$)[a-zA-Zа-яА-ЯёЁ0-9._~\-|:?#[\]\\@!%^"№$&'{}()*+,/;=]{8,30}$/gm; вот это работает по всем проверкам.

2023-11-12 10:05 UTC, ArturKhelshtein approved these changes

2023-11-13 16:16 UTC, MothersCoder approved these changes

2023-11-15 14:31 UTC, vvvolkova-92 approved these changes

2023-11-15 14:31 UTC, merged