Фильтр компаний по Городу, Услуге + пагинация
Information-platform-about-IT-companies/Front-main pull request #86
Opened 2023-11-14 03:59 UTC by gineff

Видео:
https://github.com/Information-platform-about-IT-companies/Front-main/assets/9252601/6f0ed13c-8fd3-4b66-a58a-b2d28f3e8ad0

2023-11-14 09:32 UTC, ArturKhelshtein requested changes
в целом код понравился 

и можно сделать возможность называть на текст города/сервиса для выбора чекбокса. попадать в эти маленькие квадраты сложно

и почему на странице фильтра 3 компании вроде договаривались о 10

2023-11-14 09:32 UTC, ArturKhelshtein commented on src/components/Filter/FilterTabs/FilterTabs.jsx
>        <button onClick={onClick} className="filter__tabs-button">
лучше заменить на buttonIcon. Но важнее, должен менятся цвет при разворачивании окна фильтра. а при наличии параметрова должен менятся на фильтр с крестиком, по которому будет фильтр очищатся от выбранных чекбоксов

2023-11-14 09:32 UTC, ArturKhelshtein commented on src/services/constants.js
> -    inFavorite: true,
с напианием - в избранном есть разночтения. так в бэке?

2023-11-14 09:32 UTC, ArturKhelshtein commented on src/mocks/services/categoryController.js
> +  await sleep(500);
а зачем для каждой категории разная задержка? (сервисы, города - 100; компания - 1000; категории - 500)

2023-11-14 09:32 UTC, ArturKhelshtein commented on src/pages/FilterPage/FilterPage.jsx
> +const LoadingStatus = {
почему тут это не импортировано из констант?

2023-11-14 09:32 UTC, ArturKhelshtein commented on src/pages/FilterPage/FilterPage.jsx
> +  const page = searchParams.get("page") ?? 1;
о оператор нулевого использования, до этого не видел применения :)

2023-11-14 09:39 UTC, gineff commented on src/services/constants.js
> -    inFavorite: true,
В бэке названия городов на русском

2023-11-14 09:40 UTC, gineff commented on src/pages/FilterPage/FilterPage.jsx
> +const LoadingStatus = {
Нужно будет перенести

2023-11-14 09:41 UTC, gineff commented on src/components/Filter/FilterForms/CityForm/CityForm.jsx
> +  const checkedSites = JSON.parse(searchParams.get("cities")) || [];
Да, должно быть cites

2023-11-14 09:43 UTC, gineff commented on src/components/Filter/Filter.jsx
> +    setLoadingStatus(LoadingStatus.loading);
Он стоит перед запросом fetchData. fetchData().catch(console.error) ниже

2023-11-14 13:31 UTC, ArturKhelshtein commented on src/mocks/services/categoryController.js
> +  await sleep(500);
хм, они же все асинхронные, может им вообще не нужен setTimeout (я не знаю)

2023-11-15 11:06 UTC, gineff commented on src/mocks/services/categoryController.js
> +  await sleep(500);
Пока нет контроллеров обработки запросов на сервер, sleep нужен для того чтобы увидеть прелоадер и протестировать как форма работает с асинхронными запросами

2023-11-15 12:32 UTC, gineff commented on src/components/Filter/FilterTabs/FilterTabs.jsx
> +        icon={<IconFilter cross={isOpenFilter} size="32" color={color} />}
Если свойство isOpenFilter будет false, этого react не передаст этот атрибут

2023-11-16 10:25 UTC, ArturKhelshtein commented on src/components/Filter/FilterTabs/FilterTab/FilterTab.jsx
> +      {total && <span className="filter__tab-count">{`(${total})`}</span>}
при отсутствии выбранных услуг не должно быть «0», должно просто отсутствовать число

2023-11-16 12:41 UTC, gineff commented on src/components/Filter/FilterTabs/FilterTabs.jsx
> +import { useEffect } from "react";
уберу при следующем коммите

2023-11-16 13:31 UTC, ArturKhelshtein approved these changes

2023-11-16 14:46 UTC, merged