Feauture/jest
Information-platform-about-IT-companies/Front-main pull request #89
Opened 2023-11-19 09:32 UTC by Alina1859

2023-11-19 09:34 UTC, AbdullahWins reviewed
Well Done!

2023-11-20 16:18 UTC, vvvolkova-92 requested changes

2023-11-20 16:18 UTC, vvvolkova-92 commented on src/components/Category/Category.test.jsx
> +  it("renders Category component", () => {
попробуй рендерить 1 раз при помощи beforeEach

2023-11-20 16:18 UTC, vvvolkova-92 commented on src/pages/App/App.test.jsx
> +    render(
нужно будет потом добавить контекст

2023-11-24 10:05 UTC, Alina1859 commented on src/pages/App/App.test.jsx
> +    render(
да, хотелось бы))

2023-11-24 18:38 UTC, vvvolkova-92 approved these changes

2023-11-24 18:39 UTC, merged