Feature/search continue2
Information-platform-about-IT-companies/Front-main pull request #90
Opened 2023-11-19 22:25 UTC by ArturKhelshtein

очередной подход к строке поиска.
не реализован переход на компанию.

необходимо ревью однозначно можно улучшать, прошу советов

2023-11-20 16:16 UTC, gineff commented on src/api/searchAPI/index.js
> +    const result = await fetch(`${this.baseUrl}${endpoint}`, options);
Здесь необходима конструкция try catch для обработки ошибок

2023-11-20 17:09 UTC, vvvolkova-92 requested changes

2023-11-20 17:39 UTC, vvvolkova-92 commented
Чтобы добавлять изменения в существующий комит - пиши git commit --amend --no-edit )

2023-11-22 20:10 UTC, ArturKhelshtein commented on src/api/searchAPI/index.js
> +  baseUrl: "https://dev.octopus-it.ru/api/v1/info",
это api просто лишнее уже. удаляю

2023-11-24 18:47 UTC, merged