Feature/darktheme
Information-platform-about-IT-companies/Front-main pull request #92
Opened 2023-11-22 21:31 UTC by MothersCoder

2023-11-23 09:54 UTC, vvvolkova-92 requested changes

2023-11-23 16:38 UTC, MothersCoder commented on src/UI-KIT/CompanyLogo/CompanyLogo.scss
> +    @include roboto-24(var(--text-color));
я как раз специально это сделал, так как миксин универсальный и его можно где угодно использовать, а конкретный цвет нужен в конкретном элементе

2023-11-23 16:41 UTC, MothersCoder commented on src/assets/style/variables.scss
> +$blue-night: #141420;
поправил

2023-11-23 16:43 UTC, MothersCoder commented on src/components/Category/Category.jsx
> +              withBullet={false}
убрал

2023-11-23 16:53 UTC, MothersCoder commented on src/components/Header/Header.jsx
> +import "../../assets/style/main.scss";
done

2023-11-23 16:54 UTC, MothersCoder commented on src/components/Header/Header.jsx
> -import ScrollUp from "../ScrollUp/ScrollUp";
так тут же строка удалена, значение никак не используется в компоненте

2023-11-23 18:54 UTC, MothersCoder commented on src/components/ProfileInfo/ProfileInfo.jsx
> +              <ul className="form-info-change__tooltip-container">
done

2023-11-23 18:55 UTC, MothersCoder commented on src/UI-KIT/ThemeSwitcher/ThemeSwitcher.jsx
> +  const { theme, setTheme } = useContext(ThemeContext);
может в рамках рефакторинга подумаю над этим :)

2023-11-24 18:33 UTC, vvvolkova-92 commented on src/components/Header/Header.jsx
> -import ScrollUp from "../ScrollUp/ScrollUp";
lol )))

2023-11-24 18:33 UTC, vvvolkova-92 approved these changes

2023-11-24 18:33 UTC, merged